name       : solbuild
homepage   : https://github.com/solus-project/solbuild
version    : 1.2.1
release    : 12
source     :
    - https://github.com/solus-project/solbuild/releases/download/v1.2.1/solbuild-1.2.1.tar.gz : 43d71abe563dbdb3d135d9bedb124a973bf60dbfc471cfaa1c025a39c628f4a0
license    : Apache-2.0
component  :
    - programming.tools
    - config-unstable: programming.tools
summary    :
    - Solus package build system
    - config-unstable: Unstable repo configuration for solbuild
description: |
    solbuild is a chroot based package build system, used to safely and efficiently build Solus packages from source, in a highly controlled and isolated environment. 
patterns   :
    - config-unstable: /usr/share/solbuild/99_unstable.conf
builddeps  :
    - pkgconfig(libgit2)
    - golang
rundeps    :
    - git
    - config-unstable: solbuild
build      : |
    %make
install    : |
    %make_install
    # Make it easier for Solus developers to work on unstable
    install -m 00644 data/99_unstable.conf $installdir/usr/share/solbuild/.
