name       : solbuild
homepage   : https://github.com/solus-project/solbuild
version    : 1.3.0
release    : 14
source     :
    - https://github.com/solus-project/solbuild/releases/download/v1.3.0/solbuild-1.3.0.tar.gz : 63795d5e087bfdc31f2a7b15252c834f9392d3c5f9d67035ce0b9a6dd6cde337
license    : Apache-2.0
component  :
    - programming.tools
    - config-unstable: programming.tools
summary    :
    - Solus package build system
    - config-unstable: Unstable repo configuration for solbuild
description: |
    solbuild is a chroot based package build system, used to safely and efficiently build Solus packages from source, in a highly controlled and isolated environment. 
patterns   :
    - config-unstable: /usr/share/solbuild/99_unstable.conf
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libgit2)
    - golang
rundeps    :
    - git
    - config-unstable: solbuild
setup      : |
    %patch -p1 < $pkgfiles/0001-source-simple-Use-connect-timeout-not-timeout.patch
build      : |
    %make
install    : |
    %make_install
    # Make it easier for Solus developers to work on unstable
    install -m 00644 data/99_unstable.conf $installdir/usr/share/solbuild/.
