name       : solbuild
homepage   : https://github.com/solus-project/solbuild
version    : 1.0.1
release    : 2
source     :
    - https://github.com/solus-project/solbuild/releases/download/v1.0.1/solbuild-1.0.1.tar.gz : 49f32e866cc656132f591302b211a00b8eb1fdbd466aadbbcaa5804e315b9b9a
license    : Apache-2.0
component  :
    - programming.tools
    - config-unstable: programming.tools
summary    :
    - Solus package build system
    - config-unstable: Unstable repo configuration for solbuild
description: |
    solbuild is a chroot based package build system, used to safely and efficiently build Solus packages from source, in a highly controlled and isolated environment. 
patterns   :
    - config-unstable: /usr/share/solbuild/99_unstable.conf
builddeps  :
    - pkgconfig(libgit2)
    - golang
rundeps    :
    - curl
    - git
    - config-unstable: solbuild
build      : |
    %make
install    : |
    %make_install
    # Make it easier for Solus developers to work on unstable
    install -m 00644 data/99_unstable.conf $installdir/usr/share/solbuild/.
