name       : solbuild
homepage   : https://github.com/solus-project/solbuild
version    : 1.2.0
release    : 11
source     :
    - https://github.com/solus-project/solbuild/releases/download/v1.2.0/solbuild-1.2.0.tar.gz : 86d81e68863a9ea76e495f8014d800b234fd141e2740e207cbbf9512d8cfc2f3
license    : Apache-2.0
component  :
    - programming.tools
    - config-unstable: programming.tools
summary    :
    - Solus package build system
    - config-unstable: Unstable repo configuration for solbuild
description: |
    solbuild is a chroot based package build system, used to safely and efficiently build Solus packages from source, in a highly controlled and isolated environment. 
patterns   :
    - config-unstable: /usr/share/solbuild/99_unstable.conf
builddeps  :
    - pkgconfig(libgit2)
    - golang
rundeps    :
    - curl
    - git
    - config-unstable: solbuild
setup      : |
    %patch -p1 < $pkgfiles/0001-source-simple-Greatly-increase-the-default-timeout.patch
build      : |
    %make
install    : |
    %make_install
    # Make it easier for Solus developers to work on unstable
    install -m 00644 data/99_unstable.conf $installdir/usr/share/solbuild/.
