name       : solbuild
homepage   : https://github.com/solus-project/solbuild
version    : 1.4.1
release    : 21
source     :
    - https://github.com/solus-project/solbuild/releases/download/v1.4.1/solbuild-1.4.1.tar.gz : c33bf80b7c4edeaefc223b2e1e04e7944780025f745d0f586c19c00f7cc1a981
license    : Apache-2.0
component  :
    - programming.tools
    - config-unstable : programming.tools
    - config-local-unstable : programming.tools
summary    :
    - Solus package build system
    - config-unstable : Unstable repo configuration for solbuild
    - config-local-unstable : Local repo unstable configuration for solbuild
description: |
    solbuild is a chroot based package build system, used to safely and efficiently build Solus packages from source, in a highly controlled and isolated environment.
patterns   :
    - config-unstable : /usr/share/solbuild/99_unstable.conf
    - config-local-unstable : /usr/share/solbuild/local-unstable-x86_64.profile
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libgit2)
    - golang
rundeps    :
    - abireport
    - git
    - config-unstable : solbuild
    - config-local-unstable : solbuild
build      : |
    %make
install    : |
    %make_install
    # Make it easier for Solus developers to work on unstable
    install -m 00644 data/99_unstable.conf $installdir/usr/share/solbuild/.
    install -m 00644 data/local-unstable-x86_64.profile $installdir/usr/share/solbuild/.
    install -D -m 00644 $pkgfiles/solbuild.conf $installdir/%libdir%/tmpfiles.d/solbuild.conf
