name       : solbuild
homepage   : https://github.com/solus-project/solbuild
version    : 1.1.1
release    : 8
source     :
    - https://github.com/solus-project/solbuild/releases/download/v1.1.1/solbuild-1.1.1.tar.gz : be0640da04b63d33a0cfcc8501fabafb883272e171d7fdf2c5fe60482cd9496f
license    : Apache-2.0
component  :
    - programming.tools
    - config-unstable: programming.tools
summary    :
    - Solus package build system
    - config-unstable: Unstable repo configuration for solbuild
description: |
    solbuild is a chroot based package build system, used to safely and efficiently build Solus packages from source, in a highly controlled and isolated environment. 
patterns   :
    - config-unstable: /usr/share/solbuild/99_unstable.conf
builddeps  :
    - pkgconfig(libgit2)
    - golang
rundeps    :
    - curl
    - git
    - config-unstable: solbuild
build      : |
    %make
install    : |
    %make_install
    # Make it easier for Solus developers to work on unstable
    install -m 00644 data/99_unstable.conf $installdir/usr/share/solbuild/.
