name       : solbuild
homepage   : https://github.com/solus-project/solbuild
version    : 1.5.2.0
release    : 37
source     :
    - https://github.com/getsolus/solbuild/releases/download/v1.5.2.0/solbuild-1.5.2.0.tar.xz : 292a4c8e589a60cb17b9e00b05abfc52449b5db218554a6760ed5d4ec73d6ade
license    : Apache-2.0
component  :
    - programming.tools
    - config-unstable : programming.tools
    - config-local-unstable : programming.tools
summary    :
    - Solus package build system
    - config-unstable : Unstable repo configuration for solbuild
    - config-local-unstable : Local repo unstable configuration for solbuild
description: |
    solbuild is a chroot based package build system, used to safely and efficiently build Solus packages from source, in a highly controlled and isolated environment.
patterns   :
    - config-unstable : /usr/share/solbuild/99_unstable.conf
    - config-local-unstable : /usr/share/solbuild/local-unstable-x86_64.profile
networking : yes
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libgit2)
    - golang
rundeps    :
    - git
    - config-unstable : solbuild
    - config-local-unstable : solbuild
build      : |
    %make
install    : |
    %make_install
    # Make it easier for Solus developers to work on unstable
    install -m 00644 data/99_unstable.conf $installdir/usr/share/solbuild/.
    install -m 00644 data/local-unstable-x86_64.profile $installdir/usr/share/solbuild/.
    install -D -m 00644 $pkgfiles/solbuild.conf $installdir/%libdir%/tmpfiles.d/solbuild.conf
