name       : solbuild
homepage   : https://github.com/solus-project/solbuild
version    : 1.0.0
release    : 1
source     :
    - https://github.com/solus-project/solbuild/releases/download/v1.0.0/solbuild-1.0.0.tar.gz : 2ac89469ee76aa3e6f91c00b9d9f264dcc46e014138b684552833888bd587bf2
license    : Apache-2.0
component  :
    - programming.tools
    - config-unstable: programming.tools
summary    :
    - Solus package build system
    - config-unstable: Unstable repo configuration for solbuild
description: |
    solbuild is a chroot based package build system, used to safely and efficiently build Solus packages from source, in a highly controlled and isolated environment. 
patterns   :
    - config-unstable: /usr/share/solbuild/99_unstable.conf
builddeps  :
    - pkgconfig(libgit2)
    - golang
rundeps    :
    - curl
    - git
    - config-unstable: solbuild
build      : |
    %make
install    : |
    %make_install
    # Make it easier for Solus developers to work on unstable
    install -m 00644 data/99_unstable.conf $installdir/usr/share/solbuild/.
